### ISSUE TITLE
Add CI / CD tool to build/push to npm registry

### ISSUE THREAD

**Issue by geemanjs** [lennym/govuk-react-components#1]
- [x] Select Tool (Travis CI/Circle CI?)
- [x] Allow tool access to repo
- [x] Create Build script
- [x] Add automated build for PRs
- [ ] Display status on README

**Comment by lennym** [comment]
I've set up travis in #14 although only with very basic testing.

I'm not super thrilled with the idea of automated publishes.

**Comment by geemanjs** [comment]
Lets leave it out for now then 👍
