### ISSUE TITLE
Add Prettier pre-commit hook

### ISSUE THREAD

**Issue by geemanjs** [lennym/govuk-react-components#9]
This should ensure consistent formatting across committers

- [ ] Add prettier package
- [ ] Setup pre-commit hook (lint-staged, husky)

**Comment by lennym** [comment]
I'm not sure I like this idea at all as the automated add is gonna break my usual workflow which makes heavy use of `git add -p` to make atomic commits.

I'm gonna "nope" this one for now, it's a bit *too* opinionated for my liking. I'm 100% happy with a pre-commit linter though, just not the reformatting and auto-adding.

**Comment by geemanjs** [comment]
Your Workflow++ 

We should keep an eye on this section of the documentation of lint-staged's documentation: 
https://github.com/okonet/lint-staged#reformatting-the-code

And this issue:
https://github.com/okonet/lint-staged/issues/62

Currently lint-staged processes only staged files, but can't cope with a `-p` so we can park this one for when they've fixed the above (Although I'm not sure how prettier will cope then).

Is it worth having an 'editorconfig' at the very least so we have consistent spacing.

**Comment by lennym** [comment]
I'm not really concerned with any lint task linting things that I haven't staged. I've always previously just used vanilla eslint in a pre-commit hook so not even as clever as `lint-staged` so I'm used to that. If unstaged code is failing I can always just hit it with a `-n` hammer.

I'm 100% behind the idea of strict enforcement of style, and automated reformatting, I just want the code I stage to be the code that gets committed.
